# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 555084ac8abde742a96df219871cffd4c61fc2c11d378ab7a1d274992f54d4be3e16280194aaea61731010cdbf2548e9effc49120c487463d25a40edcb02d54b

test:
  secret_key_base: d6d57bdefd546687edcb0fc1e4e1a4af1dfb9461a63533fc62218d27151514c159a53a6a22db524f9c08977e22ba844637545a69471f8b37fe3d3b6519646bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
